/*
 * AlignPlot.java
 *
 * Created on March 1, 2007, 3:41 PM
 */

package edu.scripps.pms.census.plot;

import ptolemy.plot.plotml.PlotBoxMLParser;
import ptolemy.plot.plotml.PlotMLParser;

import edu.scripps.pms.census.plot.*;
import ptolemy.plot.plotml.PlotMLParser;
import ptolemy.plot.*;
import edu.scripps.pms.census.model.*;
import edu.scripps.pms.census.hash.*;

import java.util.*;
import java.io.*;
import java.io.RandomAccessFile;
import edu.scripps.pms.census.util.*;
import edu.scripps.pms.census.model.*;

/**
 *
 * @author  rpark
 */
public class AlignPlot extends javax.swing.JPanel {
    
    /** Creates new form AlignPlot */
    public AlignPlot() {
        super();
        initComponents();
    }
    
    public void Go(String path) {
        //AlignPlot sPlot = new AlignPlot();
        //sPlot.setVisible(true);
        try {
            //original plots
            
            BufferedReader br = new BufferedReader(new FileReader(path + File.separator + "chro_out.xml"));
            StringBuffer sb = new StringBuffer();
            String eachLine;

            while( null != (eachLine=br.readLine()) )
            {
                sb.append(eachLine);
            }
            
            
           // sPlot.setVisible(true);
            //sPlot.setSize(1275,800);
            //jPanel1.setSize(1275,300);
            jPanel1.setVisible(true);
            
            //original plots
            Plot plot = new Plot();        
            PlotMLParser parser = new PlotMLParser(plot);
            plot.clear(true);
            plot.repaint();        
            parser.parse(null, sb.toString());
            jPanel1.add(plot);
            jPanel1.repaint();
            this.add(jPanel1);
            this.repaint();
            
            //aligned plots
            br = new BufferedReader(new FileReader(path + "/aligned_out.xml"));
            sb = new StringBuffer();

            while( null != (eachLine=br.readLine()) )
            {
                sb.append(eachLine);
            }

            Plot plot2 = new Plot();        
            PlotMLParser parser2 = new PlotMLParser(plot2);
            plot2.clear(true);
            //jPanel2.setSize(1275,300);
            plot2.repaint();        
            parser2.parse(null, sb.toString());
            jPanel2.setVisible(true);
            jPanel2.add(plot2);
            jPanel2.repaint();
            this.add(jPanel2);
            this.repaint();
            
            //path
            br = new BufferedReader(new FileReader(path + "/path_out.xml"));
            sb = new StringBuffer();

            while( null != (eachLine=br.readLine()) )
            {
                sb.append(eachLine);
            }

            Plot plot3 = new Plot();        
            PlotMLParser parser3 = new PlotMLParser(plot3);
            plot3.clear(true);
            //jPanel3.setSize(500,500);
            plot3.repaint();        
            parser3.parse(null, sb.toString());
            jPanel3.setVisible(true);
            jPanel3.add(plot3);
            jPanel3.repaint();
            this.add(jPanel3);
            this.repaint();
        } catch (Exception e) {   
           
        }
        System.out.println("draw align plot...");
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(100, 100));
        jSplitPane1.setDividerLocation(400);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jSplitPane2.setTopComponent(jPanel1);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jSplitPane2.setRightComponent(jPanel2);

        jSplitPane1.setLeftComponent(jSplitPane2);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jSplitPane1.setRightComponent(jPanel3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 741, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables
    
}
