/*
 * TestJFrame.java
 *
 * Created on February 28, 2007, 11:14 AM
 */

package edu.scripps.pms.census;

import edu.scripps.pms.census.dialog.*;
import javax.swing.*;
import java.io.*;

import java.awt.Container;
import java.awt.Color;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Font;
import java.awt.Dimension;

import java.awt.event.*;
import javax.swing.table.*;

import java.util.*;
import java.text.DecimalFormat;
import java.text.NumberFormat;

import edu.scripps.pms.census.util.SimpleFileNameFilter;
import edu.scripps.pms.census.io.parse.ChroXMLParser;
import edu.scripps.pms.census.io.*;
        
import edu.scripps.pms.census.hash.*;
import edu.scripps.pms.census.util.RelExFileFilter;
import edu.scripps.pms.census.util.PostCalculation;
import edu.scripps.pms.census.util.CalcUtil;

import edu.scripps.pms.census.util.io.DTASelectFilterReader;
import edu.scripps.pms.census.util.dtaselect.Protein;
import edu.scripps.pms.census.util.dtaselect.Peptide;

import edu.scripps.pms.util.spectrum.*;

import edu.scripps.pms.census.model.*;

import javax.swing.table.DefaultTableModel;

import ptolemy.plot.*;
import org.jdom.*;
import org.jdom.input.SAXBuilder;

import ptolemy.plot.plotml.PlotBoxMLParser;
import ptolemy.plot.plotml.PlotMLParser;
import edu.scripps.pms.census.plot.*;

import edu.scripps.pms.census.util.LinearRegression;
import edu.scripps.pms.census.conf.PostOptions;
import edu.scripps.pms.census.conf.Configuration;

import edu.scripps.pms.census.chroalign.*;
import gnu.trove.TIntLongHashMap;
import gnu.trove.TIntDoubleHashMap;


/**
 *
 * @author  rpark
 */
public class TestJFrame extends javax.swing.JFrame {
    
    /** Creates new form TestJFrame */
    public TestJFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(101, 101, 101)
                .add(jButton1)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(80, 80, 80)
                .add(jButton1)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    {

        final ChroProgressDialog chroProgress = new ChroProgressDialog(this, false);
        chroProgress.setLocationRelativeTo(this);
        chroProgress.setResizable(false);        
        chroProgress.setVisible(true);
        
        final long start = System.currentTimeMillis();
        
        Thread t = new Thread()
        {
            boolean isSuccessful = false;
            
            public void run()
	    {   
		try {                    

                    for(int i=0;i<10000;i++)
                        chroProgress.addMessage("aa");
                    
		}catch(Exception e) {
		    e.printStackTrace();
		}


                SwingUtilities.invokeLater(new Runnable()
                {
                public void run()
                {
                    chroProgress.setVisible(false);

                }
                });


             }  
                        
            };
            
        t.start();    
     };
                

        
    }//GEN-LAST:event_jButton1ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestJFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
    
}
