/*
 * TestPanel.java
 *
 * Created on July 19, 2006, 11:58 AM
 */

package edu.scripps.pms.census;

import javax.swing.*;
import java.io.*;
import java.awt.Color;
import java.util.*;
import java.text.DecimalFormat;
import java.awt.Toolkit;


/**
 *
 * @author  rpark
 */
public class TestPanel extends javax.swing.JFrame {
    
    /** Creates new form TestPanel */
    public TestPanel() {
        super();
        //initComponents();
    }
    
    public static void main(String[] args) throws Exception
    {
        
		UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		TestPanel t = new TestPanel();


		t.setVisible(true);
		t.validate();
		t.pack();
		//            relex.maximize();
		t.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                
                return;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("jLabel1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addContainerGap(273, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
